/**
 * Test APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('ApiController', () => {
  let controller : ApiController;

  beforeAll(() => {
    controller = new ApiController(testClient);
  });

  it('should Test Getusers', async () => {
    const response = await makeApiCall(
      () => controller.getusers(undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
