/**
 * Test APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface UsersResponse1 {
  id?: number;
  message?: string;
}

export const usersResponse1Schema: Schema<UsersResponse1> = object({
  id: ['id', optional(number())],
  message: ['message', optional(string())],
});
