/**
 * Test APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface UsersResponse {
  id?: number;
  name?: string;
}

export const usersResponseSchema: Schema<UsersResponse> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
});
