/**
 * Test APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface UsersRequest {
  /** User's username */
  username?: string;
  /** User's age */
  age: number;
  /** Whether the user is active */
  isActive?: boolean;
  /** User's rating */
  rating?: number;
  /** Signup date */
  signupDate: string;
}

export const usersRequestSchema: Schema<UsersRequest> = object({
  username: ['username', optional(string())],
  age: ['age', number()],
  isActive: ['isActive', optional(boolean())],
  rating: ['rating', optional(number())],
  signupDate: ['signupDate', string()],
});
